# Edit this file for personal application bindings.
bindd = SUPER, RETURN, Terminal, exec, desk-launch-terminal
bindd = SUPER SHIFT, F, File manager, exec, nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, desk-launch-browser
bindd = SUPER SHIFT, N, Editor, exec, desk-launch-editor

# Examples:
# bindd = SUPER SHIFT, M, Music, exec, desk-launch-or-focus 'spotify' -- spotify
# bindd = SUPER SHIFT, D, Docker, exec, desk-launch-tui lazydocker
