background {
  monitor =
  color = rgb(1a1b26)
}

general {
  ignore_empty_input = true
  hide_cursor = true
}

input-field {
  monitor =
  size = 650, 100
  position = 0, 0
  halign = center
  valign = center
  inner_color = rgb(1a1b26)
  outer_color = rgb(a9b1d6)
  outline_thickness = 4
  font_family = JetBrainsMono Nerd Font
  font_color = rgb(a9b1d6)
  placeholder_text = Enter Password
  check_color = rgb(7aa2f7)
  fail_text = <i>$FAIL ($ATTEMPTS)</i>
  rounding = 0
  shadow_passes = 0
  fade_on_empty = false
}

auth {
  fingerprint:enabled = false
}
